project:
  type: website
  
format:
  html:
    theme: 
      - litera
      - layout/css/adveconpol.scss

bibliography: data/lit/wipol_advanced.bib
csl: data/lit/wipol.csl

website:
  title: "PI 5620 Advanced Economic Policy"
  site-url: "https://mschnetzer.github.io/adveconpol/"
  
  navbar:
    pinned: true
    background: light
    foreground: "#5d8198"
    collapse: true
    right:
      - href: index.qmd
        text: About
      - href: syllabus.qmd
        text: Syllabus
      - href: schedule.qmd
        text: Schedule
      - href: visualization.qmd
        text: Chart & Report
        
  page-footer:
    right: |
      {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by {{< var author >}}
    left: |
      Made with {{< fa heart >}} and {{< fa brands r-project >}} [Quarto](https://quarto.org/)